workspace:
  base: /go
  path: src/github.com/budacom/drone-docker

pipeline:
  build:
    image: golang:1.9
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - go vet ./...
      - go test -cover ./...
      - sh .drone.sh

  publish:
    image: plugins/gcr
    repo: us.gcr.io/ops-support-191021/drone-docker
    tags: [ "latest", "17", "17.12" ]
    secrets: [ gcr_json_key ]
    dockerfile: docker/Dockerfile
    when:
      branch: master
      event: push

  publish_heroku:
    image: plugins/gcr
    repo: us.gcr.io/ops-support-191021/drone-heroku
    tags: [ "latest", "17", "17.12" ]
    secrets: [ gcr_json_key ]
    dockerfile: docker/heroku/Dockerfile
    when:
      branch: master
      event: push

  publish_gcr:
    image: plugins/gcr
    repo: us.gcr.io/ops-support-191021/drone-gcr
    tags: [ "latest", "17", "17.10" ]
    secrets: [ gcr_json_key ]
    dockerfile: docker/gcr/Dockerfile
    when:
      branch: master
      event: push

  publish_ecr:
    image: plugins/gcr
    repo: us.gcr.io/ops-support-191021/drone-ecr
    tags: [ "latest", "17", "17.10" ]
    secrets: [ gcr_json_key ]
    dockerfile: docker/ecr/Dockerfile
    when:
      branch: master
      event: push
